added cartPage, cartItem, useCart hook and changed some styles
KonstantinLigus/online-store-js pull request #34
Opened 2023-10-07 12:26 UTC by Vatrushka20

2023-10-07 20:19 UTC, KonstantinLigus requested changes

2023-10-08 09:28 UTC, Vatrushka20 commented on src/frontend/components/consumers/CartItem/CartItem.jsx
> +                src={minusIcon}
fixed

2023-10-08 09:29 UTC, Vatrushka20 commented on src/frontend/components/consumers/CartItem/CartItem.jsx
> +import plusIcon from "../../../../../public/assets/icon/icons-plus.svg";
fixed

2023-10-08 09:33 UTC, Vatrushka20 commented on src/frontend/components/consumers/CartItem/CartItem.jsx
agreed on the name in personal messages

2023-10-08 16:53 UTC, Kulyk-Volodymyr approved these changes

2023-10-09 17:05 UTC, KonstantinLigus commented on src/frontend/components/consumers/CartItem/CartItem.jsx
> +                src={minusIcon}
still occured, ou should add some breackpoint to `size` prop

2023-10-09 18:04 UTC, KonstantinLigus approved these changes

2023-10-09 18:04 UTC, merged